import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages"

import * as build from "../build/server"

// @ts-expect-error - the server build file is generated by `remix vite:build`
export const onRequest = createPagesFunctionHandler({ build })
